package com.aistudio.mediatool.core.spatial

import org.json.JSONObject
import java.io.File

object SteamAudioBridge {
    private val loadResult: Result<Unit> by lazy {
        runCatching {
            System.loadLibrary("phonon")
            System.loadLibrary("mediatool_spatial")
        }
    }

    fun render(input: File, output: File, config: SpatialAudioConfig): SpatialRenderMetrics {
        loadResult.getOrThrow()
        require(input.isFile && input.length() >= 8L) { "PCM stereo đầu vào spatial không hợp lệ" }
        output.parentFile?.mkdirs()
        output.delete()
        val value = config.normalized()
        val room = RoomReflectionNativeSpec.balanced(value.roomPreset)
        val diskBudget = SpatialDiskBudgetEstimator.requireCapacity(input, output, value)
        val response = nativeRenderRoomAware(
            inputPath = input.absolutePath,
            outputPath = output.absolutePath,
            sofaPath = value.customSofaPath.orEmpty(),
            sampleRate = SAMPLE_RATE,
            frameSize = value.frameSize,
            trajectory = value.trajectory.nativeId,
            interpolation = value.interpolation.nativeId,
            motionMode = value.motionMode.nativeId,
            reflectionIntegerPayload = room.integerPayload(),
            reflectionFloatPayload = room.floatPayload(),
            startAzimuthDeg = value.startAzimuthDeg,
            endAzimuthDeg = value.endAzimuthDeg,
            startElevationDeg = value.startElevationDeg,
            endElevationDeg = value.endElevationDeg,
            startDistanceM = value.startDistanceM,
            endDistanceM = value.endDistanceM,
            cycleSeconds = value.cycleSeconds,
            spatialBlend = value.spatialBlend,
            distanceMinM = value.distanceMinM,
            distanceRolloff = value.distanceRolloff,
            airAbsorption = value.airAbsorption,
            directivityWeight = value.directivityWeight,
            directivityPower = value.directivityPower,
            sourceYawDeg = value.sourceYawDeg,
            reverbWet = value.reverbWet,
            reverbRt60Low = value.reverbRt60Low,
            reverbRt60Mid = value.reverbRt60Mid,
            reverbRt60High = value.reverbRt60High,
            reverbEqLow = value.reverbEqLow,
            reverbEqMid = value.reverbEqMid,
            reverbEqHigh = value.reverbEqHigh,
            outputGainDb = value.outputGainDb,
            effectStartSeconds = value.effectStartSeconds,
            effectEndSeconds = value.effectEndSeconds,
        )
        val json = JSONObject(response)
        if (!json.optBoolean("ok", false)) {
            error(json.optString("error", "Steam Audio không thể render"))
        }
        require(output.isFile && output.length() > 0L) { "Steam Audio không tạo PCM đầu ra" }
        return SpatialRenderMetrics(
            frames = json.optLong("frames"),
            blocks = json.optLong("blocks"),
            tailFrames = json.optLong("tail_frames"),
            renderMs = json.optLong("render_ms"),
            inputChannels = json.optInt("input_channels", 2),
            outputChannels = json.optInt("output_channels", 2),
            stereoMode = json.optString("stereo_mode", "preserve_point_stereo"),
            inputPeak = json.float("input_peak"),
            inputPeakLeft = json.float("input_peak_left"),
            inputPeakRight = json.float("input_peak_right"),
            inputRmsDbfs = json.float("input_rms_dbfs", -160f),
            inputRmsLeftDbfs = json.float("input_rms_left_dbfs", -160f),
            inputRmsRightDbfs = json.float("input_rms_right_dbfs", -160f),
            inputCorrelation = json.float("input_correlation"),
            inputBalanceDb = json.float("input_balance_db"),
            inputDifferenceRmsDbfs = json.float("input_difference_rms_dbfs", -160f),
            inputDualMono = json.optBoolean("input_dual_mono", false),
            peakBeforeGain = json.float("peak_before_gain"),
            peakAfterGain = json.float("peak_after_gain"),
            peakAfterGainLeft = json.float("peak_after_gain_left"),
            peakAfterGainRight = json.float("peak_after_gain_right"),
            outputMainRmsBeforeGainDbfs = json.float("output_main_rms_before_gain_dbfs", -160f),
            outputMainRmsAfterGainDbfs = json.float("output_main_rms_after_gain_dbfs", -160f),
            outputTotalRmsDbfs = json.float("output_total_rms_dbfs", -160f),
            outputRmsLeftDbfs = json.float("output_rms_left_dbfs", -160f),
            outputRmsRightDbfs = json.float("output_rms_right_dbfs", -160f),
            outputCorrelation = json.float("output_correlation"),
            outputBalanceDb = json.float("output_balance_db"),
            automaticMakeupGainDb = json.float("automatic_makeup_gain_db"),
            manualOutputGainDb = json.float("manual_output_gain_db"),
            peakLimiterGainDb = json.float("peak_limiter_gain_db"),
            appliedGainDb = json.float("applied_gain_db"),
            estimatedLoudnessDeltaDb = json.float("estimated_loudness_delta_db"),
            peakCeilingDbfs = json.float("peak_ceiling_dbfs", -1f),
            nonFiniteSamples = json.optLong("nonfinite_samples"),
            clippedSamplesBeforeGain = json.optLong("clipped_samples_before_gain"),
            hrtfType = json.optString("hrtf_type", "unknown"),
            steamAudioVersion = json.optString("steam_audio_version", "unknown"),
            reflectionMode = json.optString("reflection_mode", "none"),
            roomId = json.optInt("room_id", value.roomPreset.nativeId),
            reflectionUpdates = json.optLong("reflection_updates"),
            reflectionSimulationMs = json.optLong("reflection_simulation_ms"),
            reflectionSourceClamps = json.optLong("reflection_source_clamps"),
            reflectionRays = json.optInt("reflection_rays", room.rays),
            reflectionBounces = json.optInt("reflection_bounces", room.bounces),
            reflectionOrder = json.optInt("reflection_order", room.order),
            reflectionDurationSeconds = json.float("reflection_duration_seconds", room.durationSeconds),
            trueEffectMix = json.optBoolean("true_effect_mix", false),
            diskAdditionalRequiredBytes = diskBudget.additionalRequiredBytes,
            diskUsableBytes = diskBudget.usableBytes,
            diskGuardPassed = diskBudget.hasCapacity,
        )
    }

    private fun JSONObject.float(name: String, fallback: Float = 0f): Float =
        optDouble(name, fallback.toDouble()).toFloat().takeIf(Float::isFinite) ?: fallback

    private external fun nativeRenderRoomAware(
        inputPath: String,
        outputPath: String,
        sofaPath: String,
        sampleRate: Int,
        frameSize: Int,
        trajectory: Int,
        interpolation: Int,
        motionMode: Int,
        reflectionIntegerPayload: IntArray,
        reflectionFloatPayload: FloatArray,
        startAzimuthDeg: Float,
        endAzimuthDeg: Float,
        startElevationDeg: Float,
        endElevationDeg: Float,
        startDistanceM: Float,
        endDistanceM: Float,
        cycleSeconds: Float,
        spatialBlend: Float,
        distanceMinM: Float,
        distanceRolloff: Float,
        airAbsorption: Float,
        directivityWeight: Float,
        directivityPower: Float,
        sourceYawDeg: Float,
        reverbWet: Float,
        reverbRt60Low: Float,
        reverbRt60Mid: Float,
        reverbRt60High: Float,
        reverbEqLow: Float,
        reverbEqMid: Float,
        reverbEqHigh: Float,
        outputGainDb: Float,
        effectStartSeconds: Float,
        effectEndSeconds: Float,
    ): String

    private const val SAMPLE_RATE = 48_000
}

data class SpatialRenderMetrics(
    val frames: Long,
    val blocks: Long,
    val tailFrames: Long,
    val renderMs: Long,
    val inputChannels: Int,
    val outputChannels: Int,
    val stereoMode: String,
    val inputPeak: Float,
    val inputPeakLeft: Float,
    val inputPeakRight: Float,
    val inputRmsDbfs: Float,
    val inputRmsLeftDbfs: Float,
    val inputRmsRightDbfs: Float,
    val inputCorrelation: Float,
    val inputBalanceDb: Float,
    val inputDifferenceRmsDbfs: Float,
    val inputDualMono: Boolean,
    val peakBeforeGain: Float,
    val peakAfterGain: Float,
    val peakAfterGainLeft: Float,
    val peakAfterGainRight: Float,
    val outputMainRmsBeforeGainDbfs: Float,
    val outputMainRmsAfterGainDbfs: Float,
    val outputTotalRmsDbfs: Float,
    val outputRmsLeftDbfs: Float,
    val outputRmsRightDbfs: Float,
    val outputCorrelation: Float,
    val outputBalanceDb: Float,
    val automaticMakeupGainDb: Float,
    val manualOutputGainDb: Float,
    val peakLimiterGainDb: Float,
    val appliedGainDb: Float,
    val estimatedLoudnessDeltaDb: Float,
    val peakCeilingDbfs: Float,
    val nonFiniteSamples: Long,
    val clippedSamplesBeforeGain: Long,
    val hrtfType: String,
    val steamAudioVersion: String,
    val reflectionMode: String,
    val roomId: Int,
    val reflectionUpdates: Long,
    val reflectionSimulationMs: Long,
    val reflectionSourceClamps: Long,
    val reflectionRays: Int,
    val reflectionBounces: Int,
    val reflectionOrder: Int,
    val reflectionDurationSeconds: Float,
    val trueEffectMix: Boolean,
    val diskAdditionalRequiredBytes: Long,
    val diskUsableBytes: Long,
    val diskGuardPassed: Boolean,
) {
    fun diagnosticFields(): Map<String, Any?> = mapOf(
        "frames" to frames,
        "blocks" to blocks,
        "tail_frames" to tailFrames,
        "render_ms" to renderMs,
        "input_channels" to inputChannels,
        "output_channels" to outputChannels,
        "stereo_mode" to stereoMode,
        "input_peak" to inputPeak,
        "input_peak_left" to inputPeakLeft,
        "input_peak_right" to inputPeakRight,
        "input_rms_dbfs" to inputRmsDbfs,
        "input_rms_left_dbfs" to inputRmsLeftDbfs,
        "input_rms_right_dbfs" to inputRmsRightDbfs,
        "input_correlation" to inputCorrelation,
        "input_balance_db" to inputBalanceDb,
        "input_difference_rms_dbfs" to inputDifferenceRmsDbfs,
        "input_dual_mono" to inputDualMono,
        "peak_before_gain" to peakBeforeGain,
        "peak_after_gain" to peakAfterGain,
        "peak_after_gain_left" to peakAfterGainLeft,
        "peak_after_gain_right" to peakAfterGainRight,
        "output_main_rms_before_gain_dbfs" to outputMainRmsBeforeGainDbfs,
        "output_main_rms_after_gain_dbfs" to outputMainRmsAfterGainDbfs,
        "output_total_rms_dbfs" to outputTotalRmsDbfs,
        "output_rms_left_dbfs" to outputRmsLeftDbfs,
        "output_rms_right_dbfs" to outputRmsRightDbfs,
        "output_correlation" to outputCorrelation,
        "output_balance_db" to outputBalanceDb,
        "automatic_makeup_gain_db" to automaticMakeupGainDb,
        "manual_output_gain_db" to manualOutputGainDb,
        "peak_limiter_gain_db" to peakLimiterGainDb,
        "applied_gain_db" to appliedGainDb,
        "estimated_loudness_delta_db" to estimatedLoudnessDeltaDb,
        "peak_ceiling_dbfs" to peakCeilingDbfs,
        "nonfinite_samples" to nonFiniteSamples,
        "clipped_samples_before_gain" to clippedSamplesBeforeGain,
        "hrtf_type" to hrtfType,
        "steam_audio_version" to steamAudioVersion,
        "reflection_mode" to reflectionMode,
        "room_id" to roomId,
        "reflection_updates" to reflectionUpdates,
        "reflection_simulation_ms" to reflectionSimulationMs,
        "reflection_source_clamps" to reflectionSourceClamps,
        "reflection_rays" to reflectionRays,
        "reflection_bounces" to reflectionBounces,
        "reflection_order" to reflectionOrder,
        "reflection_duration_seconds" to reflectionDurationSeconds,
        "true_effect_mix" to trueEffectMix,
        "disk_additional_required_bytes" to diskAdditionalRequiredBytes,
        "disk_usable_bytes" to diskUsableBytes,
        "disk_guard_passed" to diskGuardPassed,
    )
}
